#!/bin/bash
lb config \
--mode devuan \
--system live \
--interactive shell \
--chroot-filesystem squashfs \
--parent-mirror-bootstrap http://packages.devuan.org/merged/ \
--parent-mirror-binary http://packages.devuan.org/merged/ \
--mirror-bootstrap http://packages.devuan.org/merged/ \
--mirror-binary http://packages.devuan.org/merged/ \
--debian-installer live \
--architecture i386 \
--archive-areas "main contrib non-free" \
--apt-options "--force-yes --yes" \
--apt-recommends false \
--bootappend-live "live-config.locales=it_IT.UTF8 live-config.keyboard-layouts=it" \
--memtest memtest86+ \

